### ISSUE TITLE
Laravel 5/4/27 not work

### ISSUE THREAD

**Issue by dima-ua2009** [barryvdh/laravel-cors#217]
1)Require the barryvdh/laravel-cors package in your composer.json
2)Add the Cors\ServiceProvider to your config/app.php providers array (Barryvdh\Cors\ServiceProvider::class,)
3)To allow CORS for all your routes, add the HandleCors middleware in the $middleware property of app/Http/Kernel.php class:

protected $middleware = [
    // ...
    \Barryvdh\Cors\HandleCors::class,
];

Why dont work?

and i try add to Group middleware / route middleware but cors not work.
Help pls!

**Comment by volkanozyilmaz** [comment]
The same here.

**Comment by flxxyz** [comment]
protected $middlewareGroups = [
    'cors' =>[
            \Barryvdh\Cors\HandleCors::class,
    ]
]

### hope this helps XD

**Comment by gettosin4me** [comment]
The problem was solved for me by setting the HandleCors class as below in your kernel.php
```
'api' => [
            'throttle:60,1',
            'bindings',
            'cors' =>[
                \Barryvdh\Cors\HandleCors::class,
            ]
        ],
```
Hope this solved the problem

and also, make sure all your endpoint are grouped with middleware. unsecure endpoint can have an empty array as middleware, I was able to solve the problem that way

Hope it help someone

**Comment by barryvdh** [comment]
Can you try again with https://github.com/barryvdh/laravel-cors/releases/tag/v0.10.1 ?

Please re-open this issue when the problem still persists.
