### ISSUE TITLE
Lumen support?

### ISSUE THREAD

**Issue by dragonfire1119** [barryvdh/laravel-cors#38]
Are you going to be supporting lumen?

I released a package CORS for Lumen. https://github.com/dragonfire1119/cors-lumen Hope it helps people.

**Comment by tr33m4n** [comment]
This would be great

**Comment by barryvdh** [comment]
I haven't used Lumen yet, but it would make sense indeed.

But what doesn't work? What are the problems you encounter?

**Comment by tr33m4n** [comment]
I had to remove laravel-cors unfortunately as it was throwing up an error to do with the config_path? I think? I'll reinstall and confirm what/where

**Comment by barryvdh** [comment]
If that's the only problem, we could probably wrap that line (`$this->publishes([$configPath => config_path('cors.php')]);` in a `method_exists('config_path')` check.

**Comment by dangreaves** [comment]
I dropped you an email on this before I realised there was an open issue for it. Lumen uses `nikic/fast-route` in favour of the Symfony routing library which means that route filters cannot be used. Since middleware was removed in favour of route filters in 7de71aa777f38393365f98eccb44d8ae6c85a95a, was there a reason behind this?

**Comment by barryvdh** [comment]
Yeah the middleware didn't catch errors.. I'll have to see if I can combine hem or make a separate Lumen version.

**Comment by dragonfire1119** [comment]
@barryvdh Thanks for putting work & time it this. Hopefully you will figure out a lumen version.

**Comment by dangreaves** [comment]
Ditto @dragonfire1119. This is a nice easy package and would love to see Lumen supported at some point. Great work so far Barry :thumbsup:

**Comment by irazasyed** [comment]
+1 for Lumen. I was trying this today and was facing 500 internal error.

**Comment by dragonfire1119** [comment]
@dangreaves @irazasyed I released a package CORS for Lumen. https://github.com/dragonfire1119/cors-lumen

**Comment by barryvdh** [comment]
Yeah I should probably also go back to the middleware for Lumen, and perhaps Laravel also. And simplify the config, as most people probably don't have multiple configs for different paths anyways.

**Comment by irazasyed** [comment]
@dragonfire1119 Just installed. Thanks for sharing and building that package. Works good :+1: 

@barryvdh Yep! Besides we can manually add the middleware to the specific routes we want or group them together or even have a global one. That's best and simple too.

**Comment by dragonfire1119** [comment]
@irazasyed Great to hear that it works for you.

@barryvdh Ya I wanted to make it as simple as possible for people. When I use laravel-cors in laravel. I don't normally change anything in the cors config. I couldn't get the middleware to call on a options route. That's why I used a ServiceProvider.

**Comment by barryvdh** [comment]
I've updated to use a route middleware in 0.7.x, much simpler now.
Should also work with Lumen I guess.

**Comment by irazasyed** [comment]
@barryvdh No, It won't work with Lumen. Since it doesn't support some helper functions that are needed to get the packages working. I ended up creating a new package to add such support, so i could use any laravel package in Lumen.

Here's the one: https://github.com/irazasyed/larasupport

You should either create a new service provider just for Lumen or suggest the above package to be installed if users want to use your package in Lumen.

**Comment by barryvdh** [comment]
I'll probably fix it soon, need it for a Luemn of API anyways I'm

**Comment by barryvdh** [comment]
I added a new ServiceProvider for Lumen, see above commit.

Were a few differences, besides the helpers. Mostly in the way Middleware work and how the OPTIONS request is handled. Should be good now.

**Comment by pbvarsok** [comment]
What about an installation guide for Lumen? :D
