### ISSUE TITLE
The Preflight OPTIONS headers are not appended when executing the link

### ISSUE THREAD

**Issue by kennyyap92** [barryvdh/laravel-cors#51]
Would like to apologize because I am still new to Laravel and Cors but I am using the v0.7 pull with laravel 5.0, i manage to install everything but I am facing a problem whereby my preflight OPTIONS are not returned with the necessary headers. Look at the image below: 

![vyubb](https://cloud.githubusercontent.com/assets/13159260/8491476/f102e47c-216b-11e5-8b93-74b2e811aebe.png)

The link is being called by AngularJS v1.3.15 with $resource 

I manage to make a dirty override by adding those 3 lines in route.php but i do not want to maintain with such approach

> header("Access-Control-Allow-Origin: *");
> header("Access-Control-Allow-Headers: ACCEPT, CONTENT-TYPE, X-CSRF-TOKEN");
> header("Access-Control-Allow-Methods: GET, POST, OPTIONS, DELETE");

I wonder if someone could provide me with a guide on how to properly work this module. Thanks

I also have a topic in [Stackoverflow](http://stackoverflow.com/questions/31184740/angularjs-access-control-allow-origin-using-laravel-cors) which also records the updated I have done.

**Comment by sachintaware** [comment]
I am facing a similar issue and i am using angular as well,did you fix this? Error message is:

          Request header field Content-Type is not allowed by Access-Control-Allow-Headers in preflight response.

**Comment by loren138** [comment]
No idea what the issue was, but I swapped my allowedHeaders from what was posted above to `'allowedHeaders' => ['Origin', 'X-Requested-With', 'Content-Type', 'Accept']`, and it started working in Safari. Safari was complaining about a lack of the content-type header (which it already had in the list), but adding the others made it feel better...

So at the very least in v0.7.3 the headers are sent and setting allowedHeaders as the above made mine work.

If you are getting no headers at all, are you sure you installed the package and middleware correctly?
See https://github.com/barryvdh/laravel-cors#installation and https://github.com/barryvdh/laravel-cors#usage
You have to install it in the composer.json file, in app.php, and in either global middleware or each controller that needs CORS.
